name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true
        type: string
      changelog:
        description: 'Changelog for the release'
        required: true
        type: string

permissions:
  contents: write  

jobs:
  create-release:
    runs-on: ubuntu-latest
    if: github.actor == 'ffrazao'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

    - name: Create release tag
      run: |
        git tag "v${{ inputs.version }}"
        git push origin "v${{ inputs.version }}"

    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ inputs.version }}"
        name: "Release v${{ inputs.version }}"  # Release name
        body: ${{ inputs.changelog }}
        draft: false
        prerelease: false
