name: Create Release

# Trigger the workflow manually via the UI or API
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true
        type: string
      changelog:
        description: 'Changelog for the release'
        required: true
        type: string

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to work with the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Set up Git configuration for the release process
    - name: Set up Git
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"

    # Create a new Git tag for the release
    - name: Create release tag
      run: |
        git tag "v${{ inputs.version }}"
        git push origin "v${{ inputs.version }}"

    # Create GitHub release
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "v${{ inputs.version }}"
        release_name: "Release v${{ inputs.version }}"
        body: ${{ inputs.changelog }}
        draft: false
        prerelease: false
